version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timesheet_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timesheet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: