# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: judicial-postgres
    environment:
      POSTGRES_USER: judicial_user
      POSTGRES_PASSWORD: judicial_pass
      POSTGRES_DB: judicial_transcripts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - judicial-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: judicial-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - judicial-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: judicial-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - judicial-network

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  judicial-network:
    driver: bridge

